Repository aurora-opensource/au, pull requests merged in 2023-10, with the labels that each got.

#175 Update comparison table
  docs/alternatives/index.md
Labels: release notes: :book: documentation

#178 Add pregenerated files with all units
  BUILD.bazel
  docs/install.md
  release/BUILD.bazel
  release/au_all_units_hh_test.cc
  release/au_all_units_noio_hh_test.cc
  tools/bin/make-single-file
Labels: release notes: :hammer_and_wrench: tooling, release notes: :book: documentation

#177 Work around Core Issue 2174
  au/quantity.hh
Labels: release notes: :bug: lib (bugfix)

#176 Refine and document conversion factor policies
  au/BUILD.bazel
  au/apply_magnitude.hh
  au/apply_magnitude_test.cc
  au/quantity.hh
  au/quantity_test.cc
  docs/discussion/implementation/applying_magnitudes.md
  docs/discussion/implementation/index.md
Labels: release notes: :bug: lib (bugfix), release notes: :book: documentation

#182 Support `Zero` in `min`, `max`, and `clamp`
  au/math.hh
  au/math_test.cc
Labels: release notes: :bug: lib (bugfix)

#181 Update python deps to fix dependabot alert 5
  requirements_lock.txt
Labels: release notes: :gear: repo

#180 Update release instructions
  RELEASE.md
Labels: release notes: :book: documentation

#184 Update urllib to fix dependabot alert 6
  mkdocs.yml
  requirements_lock.txt
Labels: release notes: :gear: repo
